/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.salesvision2_0.adventureworks2014.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.salesvision2_0.adventureworks2014.service.AdventureWorks2014ProcedureExecutorService;
import com.salesvision2_0.adventureworks2014.models.procedure.*;

@RestController(value = "AdventureWorks2014.ProcedureExecutionController")
@RequestMapping("/AdventureWorks2014/procedureExecutor")
@Api(value = "ProcedureExecutionController", description = "controller class for procedure execution")
public class ProcedureExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(ProcedureExecutionController.class);

    @Autowired
    private AdventureWorks2014ProcedureExecutorService procedureService;

    @RequestMapping(value = "/procedure/execute/testproc1", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "w")
    public Testproc1Response executeTestproc1(@RequestParam(value = "deptid") Integer deptid, HttpServletRequest _request) {
        LOGGER.debug("Executing named procedure: testproc1");
        Testproc1Response _result = procedureService.executeTestproc1(deptid);
        LOGGER.debug("got the result for named procedure: testproc1, result:{}", _result);
        return _result;
    }

}


