/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.salesvision2_0.adventureworks2014.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.sql.Time;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.salesvision2_0.adventureworks2014.EmployeeDepartmentHistory;
import com.salesvision2_0.adventureworks2014.Shift;
import com.salesvision2_0.adventureworks2014.service.ShiftService;


/**
 * Controller object for domain model class Shift.
 * @see Shift
 */
@RestController("AdventureWorks2014.ShiftController")
@Api(value = "ShiftController", description = "Exposes APIs to work with Shift resource.")
@RequestMapping("/AdventureWorks2014/Shift")
public class ShiftController {

    private static final Logger LOGGER = LoggerFactory.getLogger(ShiftController.class);

    @Autowired
	@Qualifier("AdventureWorks2014.ShiftService")
	private ShiftService shiftService;

	@ApiOperation(value = "Creates a new Shift instance.")
	@RequestMapping(method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Shift createShift(@RequestBody Shift shift) {
		LOGGER.debug("Create Shift with information: {}" , shift);

		shift = shiftService.create(shift);
		LOGGER.debug("Created Shift with information: {}" , shift);

	    return shift;
	}


    @ApiOperation(value = "Returns the Shift instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Shift getShift(@PathVariable("id") Short id) throws EntityNotFoundException {
        LOGGER.debug("Getting Shift with id: {}" , id);

        Shift foundShift = shiftService.getById(id);
        LOGGER.debug("Shift details with id: {}" , foundShift);

        return foundShift;
    }

    @ApiOperation(value = "Updates the Shift instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Shift editShift(@PathVariable("id") Short id, @RequestBody Shift shift) throws EntityNotFoundException {
        LOGGER.debug("Editing Shift with id: {}" , shift.getShiftId());

        shift.setShiftId(id);
        shift = shiftService.update(shift);
        LOGGER.debug("Shift details with id: {}" , shift);

        return shift;
    }

    @ApiOperation(value = "Deletes the Shift instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteShift(@PathVariable("id") Short id) throws EntityNotFoundException {
        LOGGER.debug("Deleting Shift with id: {}" , id);

        Shift deletedShift = shiftService.delete(id);

        return deletedShift != null;
    }

    @RequestMapping(value = "/name/{name}", method = RequestMethod.GET)
    @ApiOperation(value = "Returns the matching Shift with given unique key values.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Shift getByName(@PathVariable("name") String name) {
        LOGGER.debug("Getting Shift with uniques key Name");
        return shiftService.getByName(name);
    }

    @RequestMapping(value = "/startTime-endTime", method = RequestMethod.GET)
    @ApiOperation(value = "Returns the matching Shift with given unique key values.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Shift getByStartTimeAndEndTime(@RequestParam("startTime") Time startTime, @RequestParam("endTime") Time endTime) {
        LOGGER.debug("Getting Shift with uniques key StartTimeAndEndTime");
        return shiftService.getByStartTimeAndEndTime(startTime, endTime);
    }

    /**
     * @deprecated Use {@link #findShifts(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Shift instances matching the search criteria.")
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Shift> searchShiftsByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Shifts list");
        return shiftService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Shift instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @RequestMapping(method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Shift> findShifts(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Shifts list");
        return shiftService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Shift instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @RequestMapping(value="/filter", method = RequestMethod.POST, consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Shift> filterShifts(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Shifts list");
        return shiftService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
    @RequestMapping(value = "/export/{exportType}", method = {RequestMethod.GET,  RequestMethod.POST}, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportShifts(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return shiftService.export(exportType, query, pageable);
    }

	@ApiOperation(value = "Returns the total count of Shift instances matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
	@RequestMapping(value = "/count", method = {RequestMethod.GET, RequestMethod.POST})
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countShifts( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting Shifts");
		return shiftService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@RequestMapping(value = "/aggregations", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getShiftAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return shiftService.getAggregatedValues(aggregationInfo, pageable);
    }

    @RequestMapping(value="/{id:.+}/employeeDepartmentHistories", method=RequestMethod.GET)
    @ApiOperation(value = "Gets the employeeDepartmentHistories instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<EmployeeDepartmentHistory> findAssociatedEmployeeDepartmentHistories(@PathVariable("id") Short id, Pageable pageable) {

        LOGGER.debug("Fetching all associated employeeDepartmentHistories");
        return shiftService.findAssociatedEmployeeDepartmentHistories(id, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service ShiftService instance
	 */
	protected void setShiftService(ShiftService service) {
		this.shiftService = service;
	}

}

