/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.salesvision2_0.adventureworks2014;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

public class EmployeePayHistoryId implements Serializable {

    private Integer businessEntityId;
    @Type(type = "DateTime")
    private LocalDateTime rateChangeDate;

    public Integer getBusinessEntityId() {
        return this.businessEntityId;
    }

    public void setBusinessEntityId(Integer businessEntityId) {
        this.businessEntityId = businessEntityId;
    }

    public LocalDateTime getRateChangeDate() {
        return this.rateChangeDate;
    }

    public void setRateChangeDate(LocalDateTime rateChangeDate) {
        this.rateChangeDate = rateChangeDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmployeePayHistory)) return false;
        final EmployeePayHistory employeePayHistory = (EmployeePayHistory) o;
        return Objects.equals(getBusinessEntityId(), employeePayHistory.getBusinessEntityId()) &&
                Objects.equals(getRateChangeDate(), employeePayHistory.getRateChangeDate());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBusinessEntityId(),
                getRateChangeDate());
    }
}
