/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.salesdb.models.query.*;

public interface SalesdbQueryExecutorService {

    Page<RepsCountResponse> executeRepsCount(Integer channel, Pageable pageable);

    Downloadable exportRepsCount(ExportType exportType, Integer channel, Pageable pageable);

    Page<LeadsByChannelResponse> executeLeadsByChannel(Integer channel, Pageable pageable);

    Downloadable exportLeadsByChannel(ExportType exportType, Integer channel, Pageable pageable);

    Page<LeadsCountResponse> executeLeadsCount(Integer channel, Pageable pageable);

    Downloadable exportLeadsCount(ExportType exportType, Integer channel, Pageable pageable);

    Page<SalesByEachRepResponse> executeSalesByEachRep(Integer id, Pageable pageable);

    Downloadable exportSalesByEachRep(ExportType exportType, Integer id, Pageable pageable);

    Page<CustomersRatioResponse> executeCustomersRatio(Integer year, Integer month, Pageable pageable);

    Downloadable exportCustomersRatio(ExportType exportType, Integer year, Integer month, Pageable pageable);

    Page<SalesByRepsResponse> executeSalesByReps(Integer channel, Pageable pageable);

    Downloadable exportSalesByReps(ExportType exportType, Integer channel, Pageable pageable);

    Page<WeeklyQuotesResponse> executeWeeklyQuotes(Integer year, Integer month, Pageable pageable);

    Downloadable exportWeeklyQuotes(ExportType exportType, Integer year, Integer month, Pageable pageable);

    Page<SalesRevenueAndCountResponse> executeSalesRevenueAndCount(Integer channel, Pageable pageable);

    Downloadable exportSalesRevenueAndCount(ExportType exportType, Integer channel, Pageable pageable);

    Page<EachRepCustomerWiseSalesResponse> executeEachRepCustomerWiseSales(Integer id, Pageable pageable);

    Downloadable exportEachRepCustomerWiseSales(ExportType exportType, Integer id, Pageable pageable);

    Page<WeeklyConvertedResponse> executeWeeklyConverted(Integer year, Integer month, Pageable pageable);

    Downloadable exportWeeklyConverted(ExportType exportType, Integer year, Integer month, Pageable pageable);

    Page<WeeklyFollowUpsResponse> executeWeeklyFollowUps(Integer year, Integer month, Pageable pageable);

    Downloadable exportWeeklyFollowUps(ExportType exportType, Integer year, Integer month, Pageable pageable);

    Page<SalesByChannelsResponse> executeSalesByChannels(Integer year, Integer month, Pageable pageable);

    Downloadable exportSalesByChannels(ExportType exportType, Integer year, Integer month, Pageable pageable);

    Page<WeeklySalesResponse> executeWeeklySales(Integer year, Integer month, Pageable pageable);

    Downloadable exportWeeklySales(ExportType exportType, Integer year, Integer month, Pageable pageable);

    Page<WeeklyLeadsResponse> executeWeeklyLeads(Integer year, Integer month, Pageable pageable);

    Downloadable exportWeeklyLeads(ExportType exportType, Integer year, Integer month, Pageable pageable);

    Page<RevenueHeatMapResponse> executeRevenueHeatMap(Integer year, Integer month, Pageable pageable);

    Downloadable exportRevenueHeatMap(ExportType exportType, Integer year, Integer month, Pageable pageable);

    Page<TopTrendingProductsResponse> executeTopTrendingProducts(Integer year, Integer month, Pageable pageable);

    Downloadable exportTopTrendingProducts(ExportType exportType, Integer year, Integer month, Pageable pageable);

}


