/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.salesvision2_0.myjavaservice5.controller;

import com.salesvision2_0.myjavaservice5.MyJavaService5;
import java.lang.String;
import javax.servlet.http.HttpServletRequest;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;

@RestController
@RequestMapping(value = "/myJavaService5")
public class MyJavaService5Controller {

    @Autowired
    private MyJavaService5 myJavaService5;

    @RequestMapping(value = "/sampleJavaOperation", produces = "application/json", method = RequestMethod.GET)
    public String sampleJavaOperation(@RequestParam(value = "name", required = false) String name, HttpServletRequest request) {
        return myJavaService5.sampleJavaOperation(name, request);
    }
}
