/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class CustomersRatioResponse implements Serializable {

    @JsonProperty("TYPE")
    @ColumnAlias("TYPE")
    private String type;
    @JsonProperty("PERCENT")
    @ColumnAlias("PERCENT")
    private BigInteger percent;

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public BigInteger getPercent() {
        return this.percent;
    }

    public void setPercent(BigInteger percent) {
        this.percent = percent;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CustomersRatioResponse)) return false;
        final CustomersRatioResponse customersRatioResponse = (CustomersRatioResponse) o;
        return Objects.equals(getType(), customersRatioResponse.getType()) &&
                Objects.equals(getPercent(), customersRatioResponse.getPercent());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getType(),
                getPercent());
    }
}
