/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class EachRepCustomerWiseSalesResponse implements Serializable {

    @JsonProperty("CUSTOMER")
    @ColumnAlias("CUSTOMER")
    private String customer;
    @JsonProperty("SALES")
    @ColumnAlias("SALES")
    private BigInteger sales;

    public String getCustomer() {
        return this.customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }

    public BigInteger getSales() {
        return this.sales;
    }

    public void setSales(BigInteger sales) {
        this.sales = sales;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EachRepCustomerWiseSalesResponse)) return false;
        final EachRepCustomerWiseSalesResponse eachRepCustomerWiseSalesResponse = (EachRepCustomerWiseSalesResponse) o;
        return Objects.equals(getCustomer(), eachRepCustomerWiseSalesResponse.getCustomer()) &&
                Objects.equals(getSales(), eachRepCustomerWiseSalesResponse.getSales());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCustomer(),
                getSales());
    }
}
