/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class LeadsCountResponse implements Serializable {

    @JsonProperty("LEADSCOUNT")
    @ColumnAlias("LEADSCOUNT")
    private BigInteger leadscount;

    public BigInteger getLeadscount() {
        return this.leadscount;
    }

    public void setLeadscount(BigInteger leadscount) {
        this.leadscount = leadscount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof LeadsCountResponse)) return false;
        final LeadsCountResponse leadsCountResponse = (LeadsCountResponse) o;
        return Objects.equals(getLeadscount(), leadsCountResponse.getLeadscount());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getLeadscount());
    }
}
