/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class RevenueHeatMapResponse implements Serializable {

    @JsonProperty("STATE")
    @ColumnAlias("STATE")
    private String state;
    @JsonProperty("SALES")
    @ColumnAlias("SALES")
    private BigInteger sales;
    @JsonProperty("CUSTOMERS")
    @ColumnAlias("CUSTOMERS")
    private BigInteger customers;
    @JsonProperty("LEADS")
    @ColumnAlias("LEADS")
    private BigInteger leads;
    @JsonProperty("QUOTES")
    @ColumnAlias("QUOTES")
    private BigInteger quotes;

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public BigInteger getSales() {
        return this.sales;
    }

    public void setSales(BigInteger sales) {
        this.sales = sales;
    }

    public BigInteger getCustomers() {
        return this.customers;
    }

    public void setCustomers(BigInteger customers) {
        this.customers = customers;
    }

    public BigInteger getLeads() {
        return this.leads;
    }

    public void setLeads(BigInteger leads) {
        this.leads = leads;
    }

    public BigInteger getQuotes() {
        return this.quotes;
    }

    public void setQuotes(BigInteger quotes) {
        this.quotes = quotes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RevenueHeatMapResponse)) return false;
        final RevenueHeatMapResponse revenueHeatMapResponse = (RevenueHeatMapResponse) o;
        return Objects.equals(getState(), revenueHeatMapResponse.getState()) &&
                Objects.equals(getSales(), revenueHeatMapResponse.getSales()) &&
                Objects.equals(getCustomers(), revenueHeatMapResponse.getCustomers()) &&
                Objects.equals(getLeads(), revenueHeatMapResponse.getLeads()) &&
                Objects.equals(getQuotes(), revenueHeatMapResponse.getQuotes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getState(),
                getSales(),
                getCustomers(),
                getLeads(),
                getQuotes());
    }
}
